import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as Font } from "next/font/google";
import "../styles/globals.css";

const font = Font({
  subsets: ["latin"],
  weight: "variable",
  display: "swap",
  preload: true,
  fallback: ["sans-serif"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: {
    default: "Next.js Template",
    template: "%s | Next.js Template",
  },
  description: "Generated by create next app using template",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-zinc-950 text-zinc-50 antialiased",
          font.className,
        )}
      >
        {children}
      </body>
    </html>
  );
}
